version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
        - "3000:3000"
        - "443:443"
    volumes:
        - ./moment:/moment
        - ./config/nginx:/etc/nginx/conf.d
    depends_on:
        - web

  web:
    build: .
    container_name: dg01
    command: bash -c "
        python3 manage.py collectstatic --no-input &&
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        gunicorn moment.wsgi:application -b 0:3000"
    volumes:
        - ./moment:/moment
        - ./config/gunicorn:/etc/systemd/system
  cron:
    build: .
    container_name: cg01
    command: bash -c "service cron start && python manage.py crontab add && tail -f /dev/null"
    volumes:
      ./moment:/moment
      ./config/gunicorn:/etc/systemd/system
    depends_on: web
