# Generated by Django 4.2.5 on 2023-10-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="momentpair",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="writing.story",
            ),
        ),
    ]
