# Generated by Django 4.2.5 on 2023-10-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writing", "0003_alter_story_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
