# Generated by Django 4.2.5 on 2023-10-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writing", "0005_alter_story_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
