# Generated by Django 4.2.5 on 2023-10-25 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("writing", "0007_alter_hashtag_created_at_alter_nudge_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hashtag",
            name="created_at",
        ),
    ]
