# Generated by Django 4.2.5 on 2023-10-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writing", "0009_alter_momentpair_moment_alter_momentpair_reply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="momentpair",
            name="reply",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
