# Generated by Django 4.2.5 on 2023-11-20 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("writing", "0011_remove_nudge_date_remove_nudge_is_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nudge",
            name="story",
        ),
    ]
